sudo: false
language: node_js
node_js:
- 'stable'
- '12'
- '10'
matrix:
  fast_finish: true
branches:
  only:
    - master
cache:
  directories:
  - node_modules
notifications:
  email:
    on_success: never

before_script: 'yarn linter'
script: 'yarn test'
after_script: "cat ./coverage/lcov.info | ./node_modules/.bin/coveralls"
